# Vectorize the raster Sacha Market logo into separately animatable SVG pieces (potrace).
import numpy as np, subprocess, json, re, os, sys
from PIL import Image
from scipy import ndimage
SRC, OUT = sys.argv[1], sys.argv[2]
K = 8
im = np.asarray(Image.open(SRC).convert('RGBA')).astype(float) / 255
a = im[..., 3]; rgb = im[..., :3]
L = rgb @ [0.299, 0.587, 0.114]
blk = np.clip((0.72 - L) / 0.62, 0, 1) * a
yel = np.clip(a - blk, 0, 1)
up = lambda m: np.asarray(Image.fromarray((m * 255).astype(np.uint8)).resize((m.shape[1] * K, m.shape[0] * K), Image.BICUBIC)).astype(float) / 255
B, Y = up(blk) > 0.5, up(yel) > 0.5
H8, W8 = B.shape
def trace(mask, name):
    ys, xs = np.where(mask)
    x0, x1, y0, y1 = xs.min(), xs.max() + 1, ys.min(), ys.max() + 1
    Image.fromarray(((~mask) * 255).astype(np.uint8)).convert('1').save(f'/tmp/{name}.pbm')
    subprocess.run(['potrace', f'/tmp/{name}.pbm', '-s', '-o', f'/tmp/{name}.svg', '--turdsize', '40', '--alphamax', '1.1', '--opttolerance', '0.3'], check=True)
    s = open(f'/tmp/{name}.svg').read()
    g = s[s.index('<g '):s.rindex('</g>') + 4]
    return {'id': name, 'x': x0 / K, 'y': y0 / K, 'w': (x1 - x0) / K, 'h': (y1 - y0) / K,
            'svg': f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x0} {y0} {x1 - x0} {y1 - y0}" preserveAspectRatio="none" width="100%" height="100%">{g}</svg>'}
pieces = []
# yellow: tile (largest, holes filled) and dot
lab, n = ndimage.label(Y); sizes = ndimage.sum(Y, lab, range(1, n + 1)); order = np.argsort(sizes)[::-1] + 1
tile = ndimage.binary_fill_holes(lab == order[0]); dot = lab == order[1]
pieces.append(trace(tile, 'tile')); pieces.append(trace(dot, 'dot'))
# black: S (inside tile bbox) + letters (by row, left to right)
lab, n = ndimage.label(B); objs = ndimage.find_objects(lab)
tb = pieces[0]
comps = []
for i, sl in enumerate(objs):
    m = lab == i + 1
    if m.sum() < 400: continue
    ys, xs = sl; cx = (xs.start + xs.stop) / 2 / K; cy = (ys.start + ys.stop) / 2 / K
    comps.append((cx, cy, m))
S = [c for c in comps if tb['x'] < c[0] < tb['x'] + tb['w'] and tb['y'] < c[1] < tb['y'] + tb['h']]
letters = [c for c in comps if c not in S]
Smask = np.any([c[2] for c in S], axis=0); pieces.append(trace(Smask, 'S'))
mid = np.median([c[1] for c in letters])
rows = {'sacha': sorted([c for c in letters if c[1] < mid - 10] or [c for c in letters if c[1] <= mid], key=lambda c: c[0])}
rows['market'] = sorted([c for c in letters if c not in rows['sacha']], key=lambda c: c[0])
for word, cs in rows.items():
    out = []
    for c in cs:
        ys, xs = np.where(c[2]); w = (xs.max() - xs.min()) / K
        if word == 'sacha' and w > 100:            # 's' and 'a' touch in the raster: cut at the thinnest column
            x0, x1 = xs.min(), xs.max(); col = c[2][:, x0:x1 + 1].sum(0); lo, hi = int(len(col) * 0.3), int(len(col) * 0.7)
            cut = x0 + lo + int(np.argmin(col[lo:hi])); m1 = c[2].copy(); m1[:, cut:] = False; m2 = c[2].copy(); m2[:, :cut] = False
            out += [m1, m2]
        else: out.append(c[2])
    for j, m in enumerate(out): pieces.append(trace(m, f'{word}{j}'))
# tile geometry: min-area rectangle angle from the tile outline
ys, xs = np.where(tile); pts = np.stack([xs, ys], 1).astype(float) / K
c = pts.mean(0); cov = np.cov((pts - c).T); ev, evec = np.linalg.eigh(cov)
best = None
for ang in np.arange(-20, 20, 0.1):
    r = np.deg2rad(ang); R = np.array([[np.cos(r), np.sin(r)], [-np.sin(r), np.cos(r)]]); q = (pts - c) @ R.T
    area = np.ptp(q[:, 0]) * np.ptp(q[:, 1])
    if best is None or area < best[0]: best = (area, ang, np.ptp(q[:, 0]), np.ptp(q[:, 1]))
geo = {'cx': c[0], 'cy': c[1], 'angle': best[1], 'w': best[2], 'h': best[3]}
json.dump({'W': im.shape[1], 'H': im.shape[0], 'tile': geo, 'pieces': pieces}, open(OUT + '/logo.json', 'w'))
open(OUT + '/logo.js', 'w').write('// GENERATED by vectorize.py from sacha-market-logo.webp (potrace). Logo px units (640x275).\nwindow.LOGO = ' + json.dumps({'W': im.shape[1], 'H': im.shape[0], 'tile': geo, 'pieces': pieces}) + ';\n')
print(n, 'black comps;', [ (p['id'], round(p['x']), round(p['y']), round(p['w']), round(p['h'])) for p in pieces]); print(geo)
