import {createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,timingSafeEqual} from 'node:crypto';
import {google,calendar_v3} from 'googleapis';
import {HttpsError,onCall,onRequest} from 'firebase-functions/v2/https';
import {onDocumentWritten} from 'firebase-functions/v2/firestore';
import {db} from './firebase/admin.js';
import {dayraAppUrl,googleClientId,googleClientSecret,googleEncryptionKey,googleRedirectUri} from './config.js';

const secrets=[googleClientId,googleClientSecret,googleEncryptionKey,googleRedirectUri,dayraAppUrl];
function oauth(){return new google.auth.OAuth2(googleClientId.value(),googleClientSecret.value(),googleRedirectUri.value())}
function key(){const value=Buffer.from(googleEncryptionKey.value(),'base64');if(value.length!==32)throw new Error('GOOGLE_TOKEN_ENCRYPTION_KEY debe contener 32 bytes en base64.');return value}
function encrypt(value:unknown){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);const body=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return [iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),body.toString('base64url')].join('.')}
function decrypt(value:string){const [iv,tag,body]=value.split('.').map(v=>Buffer.from(v,'base64url'));const decipher=createDecipheriv('aes-256-gcm',key(),iv);decipher.setAuthTag(tag);return JSON.parse(Buffer.concat([decipher.update(body),decipher.final()]).toString('utf8')) as Record<string,unknown>}
function signState(uid:string){const payload=Buffer.from(JSON.stringify({uid,exp:Date.now()+10*60_000,nonce:randomBytes(12).toString('hex')})).toString('base64url');const sig=createHmac('sha256',key()).update(payload).digest('base64url');return `${payload}.${sig}`}
function verifyState(state:string){const [payload,sig]=state.split('.');const expected=createHmac('sha256',key()).update(payload).digest();const actual=Buffer.from(sig||'','base64url');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new Error('Estado OAuth no válido.');const parsed=JSON.parse(Buffer.from(payload,'base64url').toString()) as {uid:string;exp:number};if(parsed.exp<Date.now())throw new Error('El enlace de Google expiró.');return parsed.uid}
async function clientFor(uid:string){const snap=await db.doc(`integrationSecrets/${uid}`).get();if(!snap.exists||!snap.data()?.googleTokens)throw new HttpsError('failed-precondition','Google Calendar no está conectado.');const client=oauth();client.setCredentials(decrypt(String(snap.data()!.googleTokens)));client.on('tokens',tokens=>{if(tokens.refresh_token||tokens.access_token)void db.doc(`integrationSecrets/${uid}`).set({googleTokens:encrypt({...client.credentials,...tokens}),updatedAt:new Date().toISOString()},{merge:true})});return client}
async function selectedCalendar(uid:string){const snap=await db.doc(`users/${uid}/integrations/google_calendar`).get();const id=snap.data()?.calendar_id;if(!id)throw new HttpsError('failed-precondition','Elige un calendario.');return String(id)}

export const beginGoogleCalendarConnection=onCall({region:'us-central1',secrets},async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Inicia sesión.');const auth=oauth();return {authUrl:auth.generateAuthUrl({access_type:'offline',prompt:'consent',scope:['https://www.googleapis.com/auth/calendar'],state:signState(request.auth.uid),include_granted_scopes:false})}});

export const googleCalendarCallback=onRequest({region:'us-central1',secrets},async(req,res)=>{try{const uid=verifyState(String(req.query.state||'')),code=String(req.query.code||'');if(!code)throw new Error('Google no devolvió un código.');const auth=oauth();const {tokens}=await auth.getToken(code);auth.setCredentials(tokens);const api=google.calendar({version:'v3',auth});const existing=await db.doc(`users/${uid}/integrations/google_calendar`).get();let calendarId=String(existing.data()?.calendar_id||''),calendarName=String(existing.data()?.calendar_name||'Dayra Planner');if(!calendarId){const created=await api.calendars.insert({requestBody:{summary:'Dayra Planner',timeZone:'America/Lima'}});if(!created.data.id)throw new Error('Google no devolvió el calendario creado.');calendarId=created.data.id;calendarName=created.data.summary||'Dayra Planner'}await Promise.all([db.doc(`integrationSecrets/${uid}`).set({googleTokens:encrypt(tokens),updatedAt:new Date().toISOString()},{merge:true}),db.doc(`users/${uid}/integrations/google_calendar`).set({id:'google_calendar',user_id:uid,provider:'google_calendar',status:'connected',calendar_id:calendarId,calendar_name:calendarName,last_synced_at:null,message:'',created_at:String(existing.data()?.created_at||new Date().toISOString()),updated_at:new Date().toISOString()},{merge:true})]);res.redirect(302,`${dayraAppUrl.value().replace(/\/$/,'')}/#M%C3%A1s`)}catch(error){res.status(400).send(error instanceof Error?error.message:'No se pudo conectar Google Calendar.')}});

function externalId(calendarId:string,eventId:string){return `google_${createHash('sha256').update(`${calendarId}:${eventId}`).digest('hex').slice(0,32)}`}
export const syncGoogleCalendar=onCall({region:'us-central1',secrets},async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Inicia sesión.');const uid=request.auth.uid,auth=await clientFor(uid),calendarId=await selectedCalendar(uid),api=google.calendar({version:'v3',auth});const response=await api.events.list({calendarId,singleEvents:true,orderBy:'startTime',timeMin:new Date(Date.now()-30*86400000).toISOString(),timeMax:new Date(Date.now()+365*86400000).toISOString(),maxResults:500});const batch=db.batch();for(const item of response.data.items||[]){if(!item.id||item.extendedProperties?.private?.dayraItemId)continue;const start=item.start?.dateTime||(item.start?.date?`${item.start.date}T00:00:00.000Z`:null),end=item.end?.dateTime||(item.end?.date?`${item.end.date}T00:00:00.000Z`:null);if(!start||!end)continue;const id=externalId(calendarId,item.id),ref=db.doc(`users/${uid}/events/${id}`);batch.set(ref,{id,user_id:uid,title:item.summary||'Sin título',description:item.description||'',category_id:null,start_at:new Date(start).toISOString(),end_at:new Date(end).toISOString(),location:item.location||'',external_id:item.id,source:'google_external',google_event_id:item.id,google_calendar_id:calendarId,sync_status:'synced',last_synced_at:new Date().toISOString(),created_at:new Date().toISOString(),updated_at:new Date().toISOString()},{merge:true})}batch.set(db.doc(`users/${uid}/integrations/google_calendar`),{last_synced_at:new Date().toISOString(),status:'connected',message:'',updated_at:new Date().toISOString()},{merge:true});await batch.commit();return {ok:true,count:response.data.items?.length||0}});

function taskTimes(task:Record<string,unknown>){if(!task.date||!task.time)return null;const start=new Date(`${task.date}T${String(task.time).slice(0,5)}:00-05:00`);if(Number.isNaN(start.getTime()))return null;return {start:start.toISOString(),end:new Date(start.getTime()+Number(task.duration||30)*60000).toISOString()}}
async function syncItem(uid:string,itemId:string,before:Record<string,unknown>,after:Record<string,unknown>|undefined,kind:'event'|'task',refPath:string){if(kind==='event'&&after?.source==='google_external')return;const oldId=String(before.google_event_id||'');if(kind==='task'&&after&&!after.sync_to_calendar&&!oldId&&after.calendar_sync_status==='disabled')return;const integration=await db.doc(`users/${uid}/integrations/google_calendar`).get();if(integration.data()?.status!=='connected')return;const auth=await clientFor(uid),calendarId=await selectedCalendar(uid),api=google.calendar({version:'v3',auth});if(!after){if(oldId)await api.events.delete({calendarId,eventId:oldId});return}if(kind==='task'&&!after.sync_to_calendar){if(oldId)await api.events.delete({calendarId,eventId:oldId});await db.doc(refPath).set({google_event_id:null,google_calendar_id:null,calendar_sync_status:'disabled',last_synced_at:new Date().toISOString()},{merge:true});return}const times=kind==='task'?taskTimes(after):{start:String(after.start_at),end:String(after.end_at)};if(!times)return;const semantic=kind==='task'?`${after.title}|${after.date}|${after.time}|${after.duration}|${after.sync_to_calendar}`:`${after.title}|${after.start_at}|${after.end_at}|${after.location}|${after.description}`;const oldSemantic=kind==='task'?`${before.title}|${before.date}|${before.time}|${before.duration}|${before.sync_to_calendar}`:`${before.title}|${before.start_at}|${before.end_at}|${before.location}|${before.description}`;const status=kind==='task'?after.calendar_sync_status:after.sync_status;if(semantic===oldSemantic&&(status==='synced'||status==='error'))return;const body:calendar_v3.Schema$Event={summary:String(after.title),description:String(after.description||after.notes||''),location:String(after.location||''),start:{dateTime:times.start},end:{dateTime:times.end},extendedProperties:{private:{dayraItemId:itemId,dayraItemType:kind}}};try{const result=oldId?await api.events.update({calendarId,eventId:oldId,requestBody:body}):await api.events.insert({calendarId,requestBody:body});await db.doc(refPath).set({google_event_id:result.data.id||oldId,google_calendar_id:calendarId,[kind==='task'?'calendar_sync_status':'sync_status']:'synced',last_synced_at:new Date().toISOString(),updated_at:new Date().toISOString()},{merge:true})}catch(error){await db.doc(refPath).set({[kind==='task'?'calendar_sync_status':'sync_status']:'error',sync_error:error instanceof Error?error.message:'Error de Google Calendar',updated_at:new Date().toISOString()},{merge:true})}}

export const syncEventToGoogle=onDocumentWritten({document:'users/{uid}/events/{eventId}',region:'us-central1',secrets},event=>syncItem(event.params.uid,event.params.eventId,event.data?.before.data()||{},event.data?.after.data(),'event',`users/${event.params.uid}/events/${event.params.eventId}`));
export const syncTaskToGoogle=onDocumentWritten({document:'users/{uid}/tasks/{taskId}',region:'us-central1',secrets},event=>syncItem(event.params.uid,event.params.taskId,event.data?.before.data()||{},event.data?.after.data(),'task',`users/${event.params.uid}/tasks/${event.params.taskId}`));
