// timeline.json (+ beats.json, audio/vo_placed.json) → cues.json (seconds) + film/data.js (window.TL / BEATS / VO).
// Run after ANY change to timeline.json, beats.json or the VO. Run from the project root.
//
// Beat → seconds uses the MEASURED grid (beats.json). Before the music exists it falls back to a nominal grid from
// timeline.bpm, so the film can be blocked out early. A cue lands on the nearest measured hit within ±40 ms of its
// beat time, otherwise on the beat itself. sfx events: { at: beat|mark, type, gain?, pitch?, pan?, what }
// Repeats: { at, to, every: beats, ... } expands to one cue per step (typing ticks, rolls).
import fs from 'node:fs';

const TL = JSON.parse(fs.readFileSync('timeline.json', 'utf8'));
const measured = fs.existsSync('beats.json');
const G = measured ? JSON.parse(fs.readFileSync('beats.json', 'utf8'))
  : { bpm: TL.bpm, beat: 60 / TL.bpm, offset: 0, beats: [], hits: [], nominal: true };
const P = G.beat || 60 / TL.bpm;
const B = G.beats || [];
const beatOf = (m) => {
  if (typeof m === 'number') return m;
  if (!(m in TL.marks)) throw new Error(`unknown mark "${m}"`);
  return TL.marks[m];
};
const beatTime = (x) => {
  if (!B.length) return (G.offset || 0) + x * P;
  if (x <= 0) return B[0] + x * P;
  const i = Math.floor(x), f = x - i;
  if (i >= B.length - 1) return B[B.length - 1] + (x - B.length + 1) * P;
  return B[i] + f * (B[i + 1] - B[i]);
};
const mulberry32 = (a) => () => { a |= 0; a = (a + 0x6D2B79F5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
const rnd = mulberry32(2026);

const events = [];
for (const ev of TL.sfx || []) {
  if (ev.every) {
    for (let x = beatOf(ev.at); x < beatOf(ev.to) - 1e-9; x += ev.every) events.push({ ...ev, at: +x.toFixed(4), mark: null });
  } else events.push({ ...ev, mark: typeof ev.at === 'string' ? ev.at : null });
}
const cues = events.map((ev) => {
  const beat = beatOf(ev.at), target = beatTime(beat);
  let best = null;
  for (const h of G.hits || []) { const d = Math.abs(h.t - target); if (d <= 0.04 && (!best || d < Math.abs(best.t - target))) best = h; }
  const t = best ? best.t : target;
  return {
    t: +t.toFixed(5), type: ev.type, gain: ev.gain ?? 0.8,
    pitch: ev.pitch ?? +(0.94 + rnd() * 0.12).toFixed(3), pan: ev.pan ?? +((rnd() - 0.5) * 0.5).toFixed(3),
    beat, mark: ev.mark, snapped_to_hit: !!best, snap_ms: +((t - target) * 1000).toFixed(2), what: ev.what || '',
  };
}).filter((c) => c.t < TL.duration).sort((a, b) => a.t - b.t);
fs.writeFileSync('cues.json', JSON.stringify({ sr: 48000, duration: TL.duration, measured, cues }, null, 1));

const VO = fs.existsSync('audio/vo_placed.json') ? JSON.parse(fs.readFileSync('audio/vo_placed.json', 'utf8')) : [];
const { hits, ...grid } = G;
fs.mkdirSync('film', { recursive: true });
fs.writeFileSync('film/data.js', `// GENERATED by scripts/sync.mjs — do not edit\nwindow.TL = ${JSON.stringify(TL)};\nwindow.BEATS = ${JSON.stringify(grid)};\nwindow.VO = ${JSON.stringify(VO)};\n`);

console.log(`grid: ${measured ? `measured ${G.bpm} bpm, ${B.length} beats` : `NOMINAL ${TL.bpm} bpm (no beats.json yet)`}`);
console.log(`cues.json: ${cues.length} cues, ${cues.filter((c) => c.snapped_to_hit).length} on measured hits · film/data.js written${VO.length ? ` (${VO.length} VO phrases)` : ''}`);
for (const c of cues) console.log(`  ${c.t.toFixed(3)}s  b${String(c.beat).padEnd(6)} ${c.type.padEnd(7)} ${c.snapped_to_hit ? 'hit ' + (c.snap_ms >= 0 ? '+' : '') + c.snap_ms + 'ms' : 'grid'}  ${c.what}`);
