export type Priority='baja'|'media'|'alta'|'critica';
export type Status='pendiente'|'en_progreso'|'completada'|'pospuesta';
export type Repeat='none'|'daily'|'weekly'|'monthly'|'weekdays';
export interface Base {id:string;user_id:string;created_at:string;updated_at:string}
export type ReminderStatus='scheduled'|'sent'|'snoozed'|'completed'|'cancelled';
export type SyncStatus='pending'|'synced'|'error'|'disabled';
export interface Task extends Base {title:string;description:string;category_id:string|null;priority:Priority;date:string|null;time:string|null;deadline:string|null;duration:number;status:Status;recurrence:Repeat;weekdays:number[];remind_at:string|null;snooze_count:number;notes:string;completed_at:string|null;parent_id:string|null;reminder_status:ReminderStatus;one_signal_notification_id:string|null;notification_sync_status:SyncStatus;sync_to_calendar:boolean;google_event_id:string|null;google_calendar_id:string|null;calendar_sync_status:SyncStatus;last_synced_at:string|null}
export interface Event extends Base {title:string;description:string;category_id:string|null;start_at:string;end_at:string;location:string;external_id:string|null;source:'internal'|'google_external';google_event_id:string|null;google_calendar_id:string|null;sync_status:SyncStatus;last_synced_at:string|null}
export interface Category extends Base {name:string;icon:string;color:string}
export interface Habit extends Base {name:string;kind:'water'|'sleep'|'exercise'|'custom';target:number;unit:string}
export interface HabitLog extends Base {habit_id:string;date:string;value:number}
export interface List extends Base {title:string;archived:boolean}
export interface ListItem extends Base {list_id:string;title:string;done:boolean;position:number}
export interface Capture extends Base {text:string;status:'inbox';scheduled:boolean}
export interface Resource extends Base {title:string;kind:'link'|'contact'|'note';value:string;notes:string}
export type Module='agenda'|'priorities'|'pending'|'habits';
export interface Preferences extends Base {modules:Module[];hidden:Module[];shortcuts:string[];timezone:string}
export interface Profile {id:string;display_name:string;email?:string;role:'user'|'admin';active:boolean;created_at:string}
export interface Integration extends Base {provider:'google_calendar'|'onesignal';status:'connected'|'not_configured'|'disconnected'|'error';calendar_id:string|null;calendar_name:string|null;last_synced_at:string|null;message:string}
export interface NotificationPreferences extends Base {enabled:boolean;permission:'default'|'granted'|'denied'|'unsupported';timezone:string}
export interface Tables {tasks:Task;events:Event;categories:Category;habits:Habit;habit_logs:HabitLog;lists:List;list_items:ListItem;quick_capture:Capture;frequent_resources:Resource;user_preferences:Preferences;integrations:Integration;notification_preferences:NotificationPreferences}
export type Table=keyof Tables;
export type Data={ [K in Table]:Tables[K][] };
export const tableNames:Table[]=['tasks','events','categories','habits','habit_logs','lists','list_items','quick_capture','frequent_resources','user_preferences','integrations','notification_preferences'];
export const emptyData=():Data=>({tasks:[],events:[],categories:[],habits:[],habit_logs:[],lists:[],list_items:[],quick_capture:[],frequent_resources:[],user_preferences:[],integrations:[],notification_preferences:[]});
export function day(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
export function shift(date:string,n:number){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);return day(d)}
export function base(user_id='demo'):Base{const stamp=new Date().toISOString();return {id:crypto.randomUUID(),user_id,created_at:stamp,updated_at:stamp}}
export const defaultModules:Module[]=['agenda','priorities','pending','habits'];
export function taskDraft(user='demo'):Task{return {...base(user),title:'',description:'',category_id:null,priority:'media',date:null,time:null,deadline:null,duration:30,status:'pendiente',recurrence:'none',weekdays:[],remind_at:null,snooze_count:0,notes:'',completed_at:null,parent_id:null,reminder_status:'cancelled',one_signal_notification_id:null,notification_sync_status:'disabled',sync_to_calendar:false,google_event_id:null,google_calendar_id:null,calendar_sync_status:'disabled',last_synced_at:null}}
export function nextOccurrence(t:Task,today=day()):string|null{if(t.recurrence==='none')return null;if(t.recurrence==='weekdays'&&!t.weekdays.length)throw new Error('Elige al menos un día de recurrencia.');let d=t.date||today;const floor=d>today?d:today;if(t.recurrence==='monthly'){const x=new Date(`${d}T12:00:00`);const wanted=x.getDate();do{x.setDate(1);x.setMonth(x.getMonth()+1);x.setDate(Math.min(wanted,new Date(x.getFullYear(),x.getMonth()+1,0).getDate()));d=day(x)}while(d<=floor);return d}do{d=shift(d,t.recurrence==='weekly'?7:1)}while(d<=floor||(t.recurrence==='weekdays'&&!t.weekdays.includes(new Date(`${d}T12:00:00`).getDay())));return d}
export function score(t:Task,today=day()){const days=t.deadline?Math.round((new Date(t.deadline+'T12:00:00').getTime()-new Date(today+'T12:00:00').getTime())/86400000):99;return ({baja:0,media:10,alta:25,critica:40}[t.priority])+(days<=0?35:days<=1?25:days<=3?12:0)+Math.min(t.snooze_count*3,12)}
export function suggestion(t:Task,today=day()){if(t.deadline&&t.deadline<today)return `Venció el ${formatDate(t.deadline)}. Revisa si necesitas cambiar la fecha.`;if(t.deadline&&t.deadline<=shift(today,1))return `Vence ${t.deadline===today?'hoy':'mañana'} y necesita aproximadamente ${t.duration} min.`;if(t.snooze_count>1)return `La has pospuesto ${t.snooze_count} veces. Puede ayudar reservarle un momento.`;return ''}
export function formatDate(d:string){return new Date(d+'T12:00:00').toLocaleDateString('es-PE',{day:'numeric',month:'short'})}
export function formatTime(d:string){return new Date(d).toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit',hour12:false})}
export function localInput(d:string){const x=new Date(d);return `${day(x)}T${String(x.getHours()).padStart(2,'0')}:${String(x.getMinutes()).padStart(2,'0')}`}
export function normalize(s:string){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
export function snoozeTime(minutes:number|'tonight',now=new Date()){const d=new Date(now);if(minutes==='tonight'){d.setHours(21,0,0,0);if(d<=now)d.setDate(d.getDate()+1)}else d.setMinutes(d.getMinutes()+minutes);return d.toISOString()}
export function freeSlots(events:Event[],date:string){const begin=new Date(`${date}T07:00:00`).getTime(),end=new Date(`${date}T22:00:00`).getTime();let cursor=Math.max(begin,date===day()?Date.now():begin);const slots:{start:string;end:string;minutes:number}[]=[];const ranges=events.map(e=>({a:Math.max(begin,Date.parse(e.start_at)),b:Math.min(end,Date.parse(e.end_at))})).filter(e=>e.b>begin&&e.a<end).sort((a,b)=>a.a-b.a);for(const e of ranges){if(e.a-cursor>=30*60000)slots.push({start:new Date(cursor).toISOString(),end:new Date(e.a).toISOString(),minutes:Math.floor((e.a-cursor)/60000)});cursor=Math.max(cursor,e.b)}if(end-cursor>=30*60000)slots.push({start:new Date(cursor).toISOString(),end:new Date(end).toISOString(),minutes:Math.floor((end-cursor)/60000)});return slots}
export function demoData():Data{const data=emptyData();const today=day();data.categories=['Universidad','Rotaciones','Guardias','Tesis','Investigación','Qx Medic','Historias clínicas','Personal','Ejercicio'].map((name,i)=>({...base(),name,icon:['GraduationCap','Stethoscope','Clock3','BookOpen','Microscope','BookOpen','Clipboard','Folder','Activity'][i],color:['#315b68','#567761','#7b6291','#7d6844'][i%4]}));data.events=[['Rotación de medicina','08:00','12:00',1,'Hospital'],['Reunión de tesis','14:00','15:00',3,'Biblioteca'],['Estudiar examen','17:30','19:00',0,'']].map(([title,start,end,cat,location])=>({...base(),title:String(title),description:'',category_id:data.categories[Number(cat)].id,start_at:new Date(`${today}T${start}:00`).toISOString(),end_at:new Date(`${today}T${end}:00`).toISOString(),location:String(location),source:'internal',external_id:null,google_event_id:null,google_calendar_id:null,sync_status:'disabled',last_synced_at:null}));data.tasks=[{...taskDraft(),title:'Estudiar Qx Medic',priority:'alta',date:today,deadline:shift(today,1),category_id:data.categories[5].id,duration:60},{...taskDraft(),title:'Revisar avances de tesis',priority:'alta',date:today,category_id:data.categories[3].id},{...taskDraft(),title:'Pedir firma de historia clínica',date:today,category_id:data.categories[6].id,remind_at:new Date(Date.now()-3600000).toISOString(),reminder_status:'sent'},{...taskDraft(),title:'Preparar materiales para la guardia',date:shift(today,1),category_id:data.categories[2].id}];data.habits=[{...base(),name:'Agua',kind:'water',target:8,unit:'vasos'},{...base(),name:'Sueño',kind:'sleep',target:8,unit:'horas'},{...base(),name:'Ejercicio',kind:'exercise',target:1,unit:'sesión'}];data.lists=[{...base(),title:'Para la guardia',archived:false},{...base(),title:'Compras',archived:false}];data.list_items=['Estetoscopio','Bata limpia','Botella de agua'].map((title,position)=>({...base(),list_id:data.lists[0].id,title,done:position===0,position}));data.user_preferences=[{...base(),modules:defaultModules,hidden:[],shortcuts:['Listas','Hábitos','Bandeja'],timezone:'America/Lima'}];return data}

