import {collection,doc,getDoc,getDocs,onSnapshot,query,runTransaction,setDoc,writeBatch,type Firestore,type Unsubscribe} from 'firebase/firestore';
import {base,emptyData,tableNames,type Data,type Table,type Tables,type Profile,type Task,shift,nextOccurrence} from './model';

const paths:Record<Table,string>={tasks:'tasks',events:'events',categories:'categories',habits:'habits',habit_logs:'habitLogs',lists:'lists',list_items:'listItems',quick_capture:'quickCapture',frequent_resources:'resources',user_preferences:'preferences',integrations:'integrations',notification_preferences:'notificationPreferences'};
const clean=<T>(value:T):T=>JSON.parse(JSON.stringify(value)) as T;

export interface Repository {load():Promise<Data>;save<K extends Table>(table:K,row:Tables[K]):Promise<Tables[K]>;remove(table:Table,id:string):Promise<void>;complete(task:Task):Promise<void>;logHabit(habit_id:string,date:string,value:number,increment:boolean):Promise<void>;convertCapture(id:string,task:Task):Promise<void>;reorderItems(a:string,b:string):Promise<void>;subscribe?(onChange:()=>void,onError:(error:Error)=>void):Unsubscribe}

export class DemoRepository implements Repository {
 constructor(public data:Data){}
 async load(){return structuredClone(this.data)}
 async save<K extends Table>(table:K,row:Tables[K]){const rows=this.data[table] as Tables[K][];const i=rows.findIndex(r=>r.id===row.id);if(i>=0)rows[i]=structuredClone(row);else rows.push(structuredClone(row));return row}
 async remove(table:Table,id:string){(this.data[table] as {id:string}[])=this.data[table].filter(r=>r.id!==id);if(table==='lists')this.data.list_items=this.data.list_items.filter(r=>r.list_id!==id);if(table==='habits')this.data.habit_logs=this.data.habit_logs.filter(r=>r.habit_id!==id);if(table==='categories'){this.data.tasks.forEach(r=>{if(r.category_id===id)r.category_id=null});this.data.events.forEach(r=>{if(r.category_id===id)r.category_id=null})}}
 async complete(task:Task){const t=this.data.tasks.find(x=>x.id===task.id);if(!t||t.status==='completada')return;const next=nextOccurrence(t);const previousReminder=t.remind_at;t.status='completada';t.completed_at=new Date().toISOString();t.remind_at=null;t.reminder_status='completed';if(next&&!this.data.tasks.some(x=>x.parent_id===t.id)){const offset=t.deadline&&t.date?Math.round((Date.parse(t.deadline+'T12:00:00')-Date.parse(t.date+'T12:00:00'))/86400000):0;const rem=previousReminder?new Date(previousReminder):null;if(rem){const nextDay=new Date(next+'T12:00:00');rem.setFullYear(nextDay.getFullYear(),nextDay.getMonth(),nextDay.getDate())}this.data.tasks.push({...t,...base(t.user_id),status:'pendiente',date:next,deadline:t.deadline?shift(next,offset):null,remind_at:rem?.toISOString()||null,reminder_status:rem?'scheduled':'cancelled',completed_at:null,parent_id:t.id,snooze_count:0})}}
 async logHabit(habit_id:string,date:string,value:number,increment:boolean){const r=this.data.habit_logs.find(x=>x.habit_id===habit_id&&x.date===date);if(r)r.value=increment?r.value+value:value;else this.data.habit_logs.push({...base(),habit_id,date,value})}
 async convertCapture(id:string,task:Task){await this.save('tasks',task);await this.remove('quick_capture',id)}
 async reorderItems(a:string,b:string){const x=this.data.list_items.find(i=>i.id===a),y=this.data.list_items.find(i=>i.id===b);if(x&&y){const p=x.position;x.position=y.position;y.position=p}}
}

export class FirebaseRepository implements Repository {
 constructor(readonly db:Firestore,readonly user:string){}
 private col(table:Table){return collection(this.db,'users',this.user,paths[table])}
 private ref(table:Table,id:string){return doc(this.db,'users',this.user,paths[table],id)}
 async load(){const data=emptyData();await Promise.all(tableNames.map(async table=>{const snap=await getDocs(query(this.col(table)));(data[table] as unknown[])=snap.docs.map(d=>clean({...d.data(),id:d.id,user_id:this.user}));}));return data}
 async save<K extends Table>(table:K,row:Tables[K]){const saved=clean({...row,user_id:this.user,updated_at:new Date().toISOString()}) as Tables[K];await setDoc(this.ref(table,row.id),saved,{merge:true});return saved}
 async remove(table:Table,id:string){const batch=writeBatch(this.db);batch.delete(this.ref(table,id));if(table==='lists'){const snap=await getDocs(this.col('list_items'));snap.docs.filter(d=>d.data().list_id===id).forEach(d=>batch.delete(d.ref))}if(table==='habits'){const snap=await getDocs(this.col('habit_logs'));snap.docs.filter(d=>d.data().habit_id===id).forEach(d=>batch.delete(d.ref))}if(table==='categories'){for(const child of ['tasks','events'] as const){const snap=await getDocs(this.col(child));snap.docs.filter(d=>d.data().category_id===id).forEach(d=>batch.update(d.ref,{category_id:null,updated_at:new Date().toISOString()}))}}await batch.commit()}
 async complete(task:Task){const currentRef=this.ref('tasks',task.id);await runTransaction(this.db,async tx=>{const snapshot=await tx.get(currentRef);if(!snapshot.exists()||snapshot.data().status==='completada')return;const current={...snapshot.data(),id:snapshot.id,user_id:this.user} as Task;const next=nextOccurrence(current);const previousReminder=current.remind_at;tx.update(currentRef,{status:'completada',completed_at:new Date().toISOString(),remind_at:null,reminder_status:'completed',updated_at:new Date().toISOString()});if(next){const childId=`${current.id}_${next}`;const childRef=this.ref('tasks',childId);const existing=await tx.get(childRef);if(!existing.exists()){const offset=current.deadline&&current.date?Math.round((Date.parse(current.deadline+'T12:00:00')-Date.parse(current.date+'T12:00:00'))/86400000):0;const reminder=previousReminder?new Date(previousReminder):null;if(reminder){const d=new Date(next+'T12:00:00');reminder.setFullYear(d.getFullYear(),d.getMonth(),d.getDate())}tx.set(childRef,clean({...current,...base(this.user),id:childId,status:'pendiente',date:next,deadline:current.deadline?shift(next,offset):null,remind_at:reminder?.toISOString()||null,reminder_status:reminder?'scheduled':'cancelled',completed_at:null,parent_id:current.id,snooze_count:0,one_signal_notification_id:null,notification_sync_status:reminder?'pending':'disabled',calendar_sync_status:current.sync_to_calendar?'pending':'disabled'}))}}})}
 async logHabit(habit_id:string,date:string,value:number,increment:boolean){const id=`${habit_id}_${date}`;const ref=this.ref('habit_logs',id);await runTransaction(this.db,async tx=>{const snap=await tx.get(ref);const now=new Date().toISOString();if(snap.exists())tx.update(ref,{value:increment?Number(snap.data().value||0)+value:value,updated_at:now});else tx.set(ref,{...base(this.user),id,habit_id,date,value,created_at:now,updated_at:now,user_id:this.user})})}
 async convertCapture(id:string,task:Task){const batch=writeBatch(this.db);batch.set(this.ref('tasks',task.id),clean({...task,user_id:this.user,updated_at:new Date().toISOString()}));batch.delete(this.ref('quick_capture',id));await batch.commit()}
 async reorderItems(a:string,b:string){const ar=this.ref('list_items',a),br=this.ref('list_items',b);await runTransaction(this.db,async tx=>{const x=await tx.get(ar),y=await tx.get(br);if(!x.exists()||!y.exists())throw new Error('Un elemento ya no está disponible.');tx.update(ar,{position:y.data().position,updated_at:new Date().toISOString()});tx.update(br,{position:x.data().position,updated_at:new Date().toISOString()})})}
 subscribe(onChange:()=>void,onError:(error:Error)=>void){let queued=false;const changed=()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;onChange()})};const stops=(['tasks','events','user_preferences'] as Table[]).map(table=>onSnapshot(this.col(table),changed,error=>onError(new Error(error.message))));return()=>stops.forEach(stop=>stop())}
}

export async function getProfile(db:Firestore,id:string):Promise<Profile>{const snapshot=await getDoc(doc(db,'users',id));if(!snapshot.exists()||snapshot.data().active===false)throw new Error('Tu cuenta todavía no tiene acceso a este espacio. Contacta al administrador.');const p=snapshot.data();return {id,display_name:String(p.name||p.display_name||'Dayra'),role:p.role==='admin'?'admin':'user',active:p.active!==false,created_at:typeof p.createdAt==='string'?p.createdAt:new Date().toISOString()}}
