"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {createUserWithEmailAndPassword,deleteUser,onAuthStateChanged,sendPasswordResetEmail,signInWithEmailAndPassword,signOut,type User} from 'firebase/auth';
import {doc,setDoc} from 'firebase/firestore';
import {configureFirebase,type FirebaseServices} from '@/firebase/client';
import {DemoRepository,FirebaseRepository,getProfile,type Repository} from './repository';
import {demoData,emptyData,type Data,type Profile,type Table,type Task} from './model';
import {cancelTaskNotification,forgetOneSignal,identifyOneSignal,syncTaskNotification} from './notifications';

function friendlyError(error:unknown,fallback:string){
 const code=typeof error==='object'&&error&&'code' in error?String(error.code):'';
 if(code==='permission-denied')return 'No tienes permiso para acceder a estos datos.';
 if(code==='unavailable'||code==='failed-precondition')return 'No pudimos conectar con tus datos. Comprueba tu conexión e inténtalo de nuevo.';
 return fallback;
}

export function useDay(){const [data,setData]=useState<Data>(emptyData);const [profile,setProfile]=useState<Profile|null>(null);const [mode,setMode]=useState<'loading'|'login'|'demo'|'live'>('loading');const [services,setServices]=useState<FirebaseServices|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [online,setOnline]=useState(true);const repo=useRef<Repository|null>(null);const repoStop=useRef<()=>void>(()=>{});const lock=useRef(false);const generation=useRef(0);const registrationGate=useRef<Promise<void>|null>(null);const notificationAttempts=useRef(new Set<string>());const syncingTasks=useRef(new Set<string>());const removedTasks=useRef(new Set<string>());
 const reload=useCallback(async()=>{if(repo.current)setData(await repo.current.load())},[]);
 useEffect(()=>{let alive=true;let authStop=()=>{};const onlineChanged=()=>setOnline(navigator.onLine);onlineChanged();window.addEventListener('online',onlineChanged);window.addEventListener('offline',onlineChanged);configureFirebase().then(s=>{if(!alive)return;setServices(s);if(!s){setMode('login');return}authStop=onAuthStateChanged(s.auth,async user=>{const g=++generation.current;repoStop.current();repoStop.current=()=>{};if(!user){notificationAttempts.current.clear();syncingTasks.current.clear();removedTasks.current.clear();repo.current=null;setData(emptyData());setProfile(null);setMode('login');return}try{if(registrationGate.current)await registrationGate.current;const p=await getProfile(s.db,user.uid);const r=new FirebaseRepository(s.db,user.uid);const d=await r.load();if(!alive||g!==generation.current)return;repo.current=r;setProfile({...p,email:user.email||undefined});setData(d);setMode('live');repoStop.current=r.subscribe?.(()=>void reload(),e=>setError(friendlyError(e,'No pudimos actualizar tus datos. Inténtalo de nuevo.')))||(()=>{});void identifyOneSignal(s.config.oneSignalAppId,user.uid).catch(()=>{})}catch(e){if(alive){setError(friendlyError(e,'No pudimos abrir tu espacio. Inténtalo de nuevo.'));setMode('login');await signOut(s.auth).catch(()=>{})}}})}).catch(e=>{if(alive){setError(friendlyError(e,'No pudimos conectar con Firebase.'));setMode('login')}});return()=>{alive=false;repoStop.current();authStop();window.removeEventListener('online',onlineChanged);window.removeEventListener('offline',onlineChanged)}},[reload]);
 const run=useCallback(async(action:(r:Repository)=>Promise<unknown>)=>{if(lock.current)return false;if(!repo.current){setError('Inicia sesión para continuar.');return false}lock.current=true;setBusy(true);setError('');try{await action(repo.current);await reload();return true}catch(e){setError(friendlyError(e,'No pudimos guardar. Inténtalo de nuevo.'));return false}finally{lock.current=false;setBusy(false)}},[reload]);
 useEffect(()=>{if(mode!=='live'||!services?.auth.currentUser||!online)return;const currentRepo=repo.current;if(!currentRepo)return;const signatureOf=(task:Task)=>[task.id,task.title,task.time,task.remind_at,task.status,task.reminder_status,task.one_signal_notification_id,task.notification_sync_status,task.updated_at].join('|');for(const task of data.tasks){const needsSchedule=task.notification_sync_status==='pending'||task.notification_sync_status==='error';const needsCancellation=Boolean(task.one_signal_notification_id)&&(!task.remind_at||task.status==='completada'||task.reminder_status==='cancelled'||task.reminder_status==='completed');if((!needsSchedule&&!needsCancellation)||removedTasks.current.has(task.id)||syncingTasks.current.has(task.id))continue;const signature=signatureOf(task);if(notificationAttempts.current.has(signature))continue;notificationAttempts.current.add(signature);syncingTasks.current.add(task.id);void (async()=>{try{const token=await services.auth.currentUser?.getIdToken();if(!token)return;const synced=await syncTaskNotification(token,task);const latest=(await currentRepo.load()).tasks.find(item=>item.id===task.id);if(removedTasks.current.has(task.id)||!latest||signatureOf(latest)!==signature){if(synced.notificationId)await cancelTaskNotification(token,{...task,one_signal_notification_id:synced.notificationId});return}const saved=await currentRepo.save('tasks',{...latest,one_signal_notification_id:synced.notificationId,notification_sync_status:synced.syncStatus,reminder_status:synced.reminderStatus});if(synced.deferred)notificationAttempts.current.add(signatureOf(saved));await reload()}catch(caught){const latest=(await currentRepo.load().catch(()=>null))?.tasks.find(item=>item.id===task.id);if(latest&&signatureOf(latest)===signature){const failed=await currentRepo.save('tasks',{...latest,notification_sync_status:'error'}).catch(()=>null);if(failed)notificationAttempts.current.add(signatureOf(failed))}setError(caught instanceof Error?`La tarea se guardó, pero su recordatorio falló: ${caught.message}`:'La tarea se guardó, pero no pudimos programar su recordatorio.')}finally{syncingTasks.current.delete(task.id);void reload()}})()}},[data.tasks,mode,online,reload,services]);
 const completeTask=useCallback((task:Task)=>run(async r=>{await r.complete(task);if(mode==='live'&&services?.auth.currentUser&&task.one_signal_notification_id){const token=await services.auth.currentUser.getIdToken();const synced=await syncTaskNotification(token,{...task,status:'completada',remind_at:null,reminder_status:'completed'});await r.save('tasks',{...task,status:'completada',completed_at:new Date().toISOString(),remind_at:null,reminder_status:synced.reminderStatus,one_signal_notification_id:synced.notificationId,notification_sync_status:synced.syncStatus})}}),[mode,run,services]);
 const removeItem=useCallback(async(table:Table,id:string)=>{if(table==='tasks')removedTasks.current.add(id);const removed=await run(async r=>{if(table==='tasks'&&mode==='live'&&services?.auth.currentUser){const task=data.tasks.find(item=>item.id===id);if(task?.one_signal_notification_id){const token=await services.auth.currentUser.getIdToken();await cancelTaskNotification(token,task)}}await r.remove(table,id)});if(!removed)removedTasks.current.delete(id);return removed},[data.tasks,mode,run,services]);
 const login=useCallback(async(email:string,password:string)=>{if(!services)throw new Error('Firebase no está configurado.');await signInWithEmailAndPassword(services.auth,email,password)},[services]);
 const register=useCallback(async(name:string,email:string,password:string)=>{if(!services)throw new Error('Firebase no está configurado.');let release=()=>{};let created:User|null=null;registrationGate.current=new Promise<void>(resolve=>{release=resolve});try{const credential=await createUserWithEmailAndPassword(services.auth,email,password);created=credential.user;const stamp=new Date().toISOString();await setDoc(doc(services.db,'users',created.uid),{uid:created.uid,email:created.email||email,name,role:'user',active:true,createdAt:stamp,updatedAt:stamp})}catch(error){if(created)await deleteUser(created).catch(()=>{});throw error}finally{release();registrationGate.current=null}},[services]);
 const resetPassword=useCallback(async(email:string)=>{if(!services)throw new Error('Firebase no está configurado.');await sendPasswordResetEmail(services.auth,email)},[services]);
 const startDemo=useCallback(()=>{generation.current++;repoStop.current();repo.current=new DemoRepository(demoData());setData(structuredClone((repo.current as DemoRepository).data));setProfile({id:'demo',display_name:'Dayra',role:'user',active:true,created_at:new Date().toISOString()});setMode('demo');setError('')},[]);
 const logout=useCallback(async()=>{if(mode==='live'&&services){await forgetOneSignal(services.config.oneSignalAppId).catch(()=>{});await signOut(services.auth)}generation.current++;repoStop.current();repo.current=null;setData(emptyData());setProfile(null);setMode('login')},[mode,services]);
 return {data,profile,mode,services,error,setError,busy,online,run,completeTask,removeItem,startDemo,logout,reload,login,register,resetPassword};
}
