"use client";
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Choice,Field} from './ui';
import {base,day,localInput,taskDraft,type Tables,type Category,type Task,type Event,type Habit,type Resource} from '@/lib/day/model';
import {findAvailableTimeSlots} from '@/lib/day/integrations';
export type Editable='tasks'|'events'|'lists'|'habits'|'categories'|'frequent_resources';
export type EditRow=Tables[Editable];
export interface Editing {table:Editable;row:EditRow;isNew:boolean}
const labels:Record<Editable,string>={tasks:'tarea',events:'evento',lists:'lista',habits:'hábito',categories:'categoría',frequent_resources:'recurso'};
export function newRow(table:Editable,user:string):EditRow{switch(table){case 'tasks':return taskDraft(user);case 'events':{const s=new Date();s.setMinutes(0,0,0);s.setHours(s.getHours()+1);return {...base(user),title:'',description:'',category_id:null,start_at:s.toISOString(),end_at:new Date(s.getTime()+3600000).toISOString(),location:'',external_id:null,source:'internal',google_event_id:null,google_calendar_id:null,sync_status:'pending',last_synced_at:null}}case 'lists':return {...base(user),title:'',archived:false};case 'habits':return {...base(user),name:'',kind:'custom',target:1,unit:'veces'};case 'categories':return {...base(user),name:'',icon:'Folder',color:'#315b68'};case 'frequent_resources':return {...base(user),title:'',kind:'link',value:'',notes:''}}}
export function Editor({editing,categories,events=[],busy,onClose,onSave,onDelete}:{editing:Editing;categories:Category[];events?:Event[];busy:boolean;onClose:()=>void;onSave:(r:EditRow)=>Promise<boolean>;onDelete:()=>void}){const [row,setRow]=useState<EditRow>(editing.row);const [error,setError]=useState('');const [conflict,setConflict]=useState<Event|null>(null);const patch=(key:string,value:unknown)=>setRow(r=>({...r,[key]:value}));const {table,isNew}=editing;const name='name' in row?row.name:row.title;const task=row as Task,event=row as Event,habit=row as Habit,category=row as Category,resource=row as Resource;const categoryField=<Choice label="Categoría" value={('category_id' in row&&row.category_id)||'none'} onChange={v=>patch('category_id',v==='none'?null:v)} options={[{value:'none',label:'Sin categoría'},...categories.map(c=>({value:c.id,label:c.name}))]}/>;
 async function save(force=false){setError('');setConflict(null);if(!name.trim()){setError('Escribe un título para continuar.');return}if(table==='events'&&(!event.start_at||!event.end_at||Date.parse(event.end_at)<=Date.parse(event.start_at))){setError('El final debe ser posterior al inicio.');return}if(table==='events'&&!force){const overlap=events.find(other=>other.id!==event.id&&event.start_at<other.end_at&&event.end_at>other.start_at);if(overlap){setConflict(overlap);return}}if(table==='tasks'&&task.recurrence==='weekdays'&&!task.weekdays.length){setError('Elige al menos un día para repetir.');return}if(table==='frequent_resources'&&resource.kind==='link'&&!/^https?:\/\//i.test(resource.value)){setError('El enlace debe comenzar con https:// o http://.');return}let clean={...row,...('name' in row?{name:name.trim()}:{title:name.trim()})} as EditRow;if(table==='tasks'){const original=editing.row as Task;const changed=['title','time','remind_at','status','reminder_status'].some(key=>task[key as keyof Task]!==original[key as keyof Task]);clean={...task,title:name.trim(),notification_sync_status:task.remind_at&&(changed||task.notification_sync_status==='error')?'pending':task.remind_at?task.notification_sync_status:'disabled'} as EditRow}if(await onSave(clean))onClose()}
 async function submit(e:React.FormEvent){e.preventDefault();await save()}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="editor"><DialogTitle>{isNew?'Crear':'Editar'} {labels[table]}</DialogTitle><DialogDescription>{table==='tasks'?'Empieza por el título. Los demás detalles son opcionales.':'Guarda lo que necesitas tener a mano.'}</DialogDescription><form onSubmit={submit} className="form-stack"><Field label={table==='categories'||table==='habits'?'Nombre':'Título'}><input autoFocus maxLength={240} required value={name} onChange={e=>patch('name' in row?'name':'title',e.target.value)} placeholder={table==='tasks'?'¿Qué necesitas hacer?':undefined}/></Field>
 {table==='tasks'&&<><div className="form-grid"><Choice label="Prioridad" value={task.priority} onChange={v=>patch('priority',v)} options={[{value:'baja',label:'Baja'},{value:'media',label:'Media'},{value:'alta',label:'Alta'},{value:'critica',label:'Crítica'}]}/><Field label="Día planificado"><input type="date" value={task.date||''} onChange={e=>patch('date',e.target.value||null)}/></Field></div><details open={!isNew}><summary>Más detalles</summary><div className="form-stack">{categoryField}<div className="form-grid"><Field label="Hora (opcional)"><input type="time" value={task.time||''} onChange={e=>patch('time',e.target.value||null)}/></Field><Field label="Duración en minutos"><input type="number" min="1" max="1440" required value={task.duration} onChange={e=>patch('duration',Number(e.target.value))}/></Field><Field label="Fecha límite"><input type="date" value={task.deadline||''} onChange={e=>patch('deadline',e.target.value||null)}/></Field><Choice label="Estado" value={task.status} onChange={v=>patch('status',v)} options={[{value:'pendiente',label:'Pendiente'},{value:'en_progreso',label:'En progreso'},{value:'pospuesta',label:'Pospuesta'},...(task.status==='completada'?[{value:'completada',label:'Completada'}]:[])]}/></div><Field label="Recordármelo"><input type="datetime-local" value={task.remind_at?localInput(task.remind_at):''} onChange={e=>{patch('remind_at',e.target.value?new Date(e.target.value).toISOString():null);patch('reminder_status',e.target.value?'scheduled':'cancelled');patch('notification_sync_status',e.target.value?'pending':'disabled')}}/></Field><label className="settings-row"><Checkbox checked={task.sync_to_calendar} disabled={!task.date||!task.time} onCheckedChange={yes=>{patch('sync_to_calendar',!!yes);patch('calendar_sync_status',yes?'pending':'disabled')}}/> Añadir como bloque a Google Calendar</label><small>Requiere fecha y hora. Firestore guarda primero; los servicios se sincronizan después.</small><Choice label="Repetir" value={task.recurrence} onChange={v=>patch('recurrence',v)} options={[{value:'none',label:'No se repite'},{value:'daily',label:'Cada día'},{value:'weekly',label:'Cada semana'},{value:'monthly',label:'Cada mes'},{value:'weekdays',label:'Días de la semana'}]}/>{task.recurrence==='weekdays'&&<div className="weekday-picks">{['D','L','M','X','J','V','S'].map((n,i)=><label key={i}><Checkbox aria-label={['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'][i]} checked={task.weekdays.includes(i)} onCheckedChange={yes=>patch('weekdays',yes?[...task.weekdays,i]:task.weekdays.filter(x=>x!==i))}/>{n}</label>)}</div>}<Field label="Descripción"><textarea maxLength={4000} rows={2} value={task.description} onChange={e=>patch('description',e.target.value)}/></Field><Field label="Notas"><textarea maxLength={4000} rows={2} value={task.notes} onChange={e=>patch('notes',e.target.value)}/></Field></div></details></>}
 {table==='events'&&<><div className="form-grid"><Field label="Inicio"><input required type="datetime-local" value={event.start_at?localInput(event.start_at):''} onChange={e=>patch('start_at',e.target.value?new Date(e.target.value).toISOString():'')}/></Field><Field label="Final"><input required type="datetime-local" value={event.end_at?localInput(event.end_at):''} onChange={e=>patch('end_at',e.target.value?new Date(e.target.value).toISOString():'')}/></Field></div>{categoryField}<Field label="Lugar"><input value={event.location} maxLength={240} onChange={e=>patch('location',e.target.value)}/></Field><Field label="Notas"><textarea value={event.description} maxLength={4000} onChange={e=>patch('description',e.target.value)}/></Field></>}
 {table==='habits'&&<><Choice label="Tipo de hábito" value={habit.kind} onChange={v=>patch('kind',v)} options={[{value:'custom',label:'Personalizado'},{value:'water',label:'Agua'},{value:'sleep',label:'Sueño'},{value:'exercise',label:'Ejercicio'}]}/><div className="form-grid"><Field label="Meta diaria"><input required type="number" min="0.25" max="1000" step="0.25" value={habit.target} onChange={e=>patch('target',Number(e.target.value))}/></Field><Field label="Unidad"><input required maxLength={30} value={habit.unit} onChange={e=>patch('unit',e.target.value)}/></Field></div></>}
 {table==='categories'&&<><Choice label="Icono" value={category.icon} onChange={v=>patch('icon',v)} options={['Folder','GraduationCap','Stethoscope','Clock3','BookOpen','Microscope','Clipboard','Activity'].map(value=>({value,label:({Folder:'Carpeta',GraduationCap:'Universidad',Stethoscope:'Medicina',Clock3:'Reloj',BookOpen:'Libro',Microscope:'Investigación',Clipboard:'Portafolio',Activity:'Actividad'}[value]||value)}))}/><Field label="Color"><input type="color" value={category.color} onChange={e=>patch('color',e.target.value)}/></Field></>}
 {table==='frequent_resources'&&<><Choice label="Tipo" value={resource.kind} onChange={v=>patch('kind',v)} options={[{value:'link',label:'Enlace'},{value:'contact',label:'Contacto'},{value:'note',label:'Información'}]}/><Field label={resource.kind==='link'?'Enlace':resource.kind==='contact'?'Teléfono o correo':'Información'}><textarea required maxLength={8000} value={resource.value} onChange={e=>patch('value',e.target.value)} placeholder={resource.kind==='link'?'https://':undefined}/></Field><Field label="Notas"><textarea maxLength={4000} value={resource.notes} onChange={e=>patch('notes',e.target.value)}/></Field></>}
 {conflict&&<div className="notice" role="alert"><strong>Tienes un conflicto con {conflict.title}.</strong><div className="snooze-buttons"><button type="button" className="secondary" onClick={()=>{const duration=Math.max(15,Math.round((Date.parse(event.end_at)-Date.parse(event.start_at))/60000));const slots=findAvailableTimeSlots({date:day(new Date(event.start_at)),duration,existingEvents:events.filter(e=>e.id!==event.id)});if(slots[0])setRow(r=>({...r,start_at:slots[0].start,end_at:slots[0].end}));setConflict(null)}}>Buscar otro horario</button><button type="button" className="secondary" onClick={()=>{const duration=Date.parse(event.end_at)-Date.parse(event.start_at),start=Date.parse(conflict.end_at);setRow(r=>({...r,start_at:new Date(start).toISOString(),end_at:new Date(start+duration).toISOString()}));setConflict(null)}}>Programar después</button><button type="button" className="secondary" onClick={()=>void save(true)}>Programar de todas formas</button></div></div>}{error&&<p role="alert" className="error-box">{error}</p>}<div className="form-actions">{!isNew&&<button type="button" className="danger" disabled={busy} onClick={onDelete}>Eliminar</button>}<button type="button" className="secondary" onClick={onClose} disabled={busy}>Cancelar</button><button className="primary" type="submit" disabled={busy}>{busy?'Guardando…':'Guardar'}</button></div></form></DialogContent></Dialog>
}

